# -*- coding: utf-8 -*-
"""Copy of Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wS0R6bRlWkhrhtsFbvtwE-xIPa7fqgLR
"""

from transformers import pipeline

generator = pipeline("text-generation", model="gpt2")

prompt = "The future of Artificial Intelligence"

result = generator(
    prompt,
    max_length=100,
    num_return_sequences=1
)

print(result[0]["generated_text"])